import { SpendCategory, TransactionType } from "@prisma/client";

export type CategorizeInput = {
  description: string;
  transactionType?: TransactionType | "DEBIT" | "CREDIT";
};

type Rule = {
  category: SpendCategory;
  // match if ANY pattern matches
  anyOf: (RegExp | string)[];
  // higher wins when multiple match
  priority: number;
};

function rx(s: string) {
  return new RegExp(s, "i");
}

// Keep this list small but credible for MVP.
// You can add more later without changing architecture.
export const AUTO_CATEGORIZE_RULES: Rule[] = [
  // INCOME (credit + payroll-like)
  {
    category: SpendCategory.INCOME,
    priority: 1000,
    anyOf: [
      rx("\\bpayroll\\b"),
      rx("\\bsalary\\b"),
      rx("\\bpay\\s?stub\\b"),
      rx("\\bdirect\\s?deposit\\b"),
      rx("\\bdeposit\\b"),
      rx("\\bemployer\\b"),
      rx("\\binterac\\s?etransfer\\b.*(received|deposit)"),
    ],
  },

  // TRANSFER / E-TRANSFER (often not "spending")
  {
    category: SpendCategory.TRANSFER,
    priority: 900,
    anyOf: [
      rx("\\betransfer\\b"),
      rx("\\be-?transfer\\b"),
      rx("\\binterac\\b"),
      rx("\\btransfer\\b"),
      rx("\\bpayment\\b.*(to|from)"),
    ],
  },

  // GROCERIES
  {
    category: SpendCategory.GROCERIES,
    priority: 800,
    anyOf: [
      "WALMART",
      "COSTCO",
      "NO FRILLS",
      "LOBLAWS",
      "METRO",
      "FRESHCO",
      "SUPERSTORE",
      "SOBEYS",
      "SAFEWAY",
      "WHOLE FOODS",
      "ZEHRS",
      "INDIA FOOD AND GROCERY",
      "KWC INDIAN GROCERY",
      "FARAH MARKET",
      "LIDL",
      "ALDI",
      "FARM BOY",
      "GIANT TIGER",
      "FOOD BASICS",
      "LONGO'S",
      "FOOD BASICS",
      "REAL CANADIAN SUPERSTORE",
      "RCSS",
      "FARM BOY",
      "LONGO'S",
      "LONGOS",
      "GIANT TIGER",
      "NATIONS FRESH FOODS",
      "T&T",
      "T AND T",
      "FRESH MARKET",
      "SAVE ON FOODS",
      "SAVE-ON-FOODS",
      "CO-OP",
      "COOP",
      "MARCHE ADONIS",
      "ADONIS",
      "PUSATERI'S",
      "PUSATERIS",
      "FORTINOS",
      "VALU-MART",
      "VALU MART",
      "MARCHÉ",
      "MARCHE",
      "HIGHLAND FARMS",
      "ORGANIC GARAGE",
    ],
  },

  // FOOD AND DINING
  {
    category: SpendCategory.FOOD_AND_DINING,
    priority: 750,
    anyOf: [
      "TIM HORTONS",
      "STARBUCKS",
      "MCDONALD",
      "SUBWAY",
      "PIZZA",
      "BURGER",
      "RESTAURANT",
      "CAFE",
      "DOORDASH",
      "UBER EATS",
      "SKIPTHEDISHES",
      "CHERRY",
      "GINO",
      "UBEREATS",
      "SOBO",
      "POPEYES",
      "KFC",
      "A&W",
      "WENDY",
      "DOMINOS",
      "TACO BELL",
      "DOMINO'S",
      "DOMINOS",
      "PIZZA PIZZA",
      "PAPA JOHNS",
      "PAPA JOHN'S",
      "LITTLE CAESARS",
      "HARVEYS",
      "HARVEY'S",
      "MARY BROWN'S",
      "MARY BROWNS",
      "OSMOS",
      "OSMOW'S",
      "OSMOWS",
      "LAZEEZ",
      "SHAWARMA",
      "BURRITO BOYZ",
      "BURRITO BOY",
      "BARBURRITO",
      "BURGER KING",
      "A & W",
      "A&W",
      "DAIRY QUEEN",
      "DQ",
      "FRESHII",
      "PANERA",
      "SECOND CUP",
      "CHATIME",
      "COCO FRESH TEA",
      "BUBBLE TEA",
      "BOOSTER JUICE",
      "JIMMY THE GREEK",
      "MANDARIN",
      "SWISS CHALET",
      "EAST SIDE MARIO'S",
      "EAST SIDE MARIOS",
    ],
  },

  // TRANSPORTATION
  {
    category: SpendCategory.TRANSPORTATION,
    priority: 700,
    anyOf: [
      rx("^uber\\b"),
      rx("\\blyft\\b"),
      rx("\\bpresto\\b"),
      rx("\\bgas\\b"),
      "SHELL",
      "ESSO",
      "PETRO",
      "HUSKY",
      "GO TRANSIT",
      "VIA RAIL",
      "AIR CANADA",
      "WESTJET",
      "ULTRAMAR",
      "PIONEER",
      "CIRCLE K",
      "CHEVRON",
      "PARKING",
      "GREEN P",
      "PRESTO",
      "GO TRAIN",
      "GO BUS",
      "TTC",
      "OC TRANSPO",
      "MIWAY",
      "BRAMPTON TRANSIT",
      "YRT",
      "UP EXPRESS",
      "PARK N FLY",
      "PARK'N FLY",
    ],
  },

  // ENTERTAINMENT
  {
    category: SpendCategory.ENTERTAINMENT,
    priority: 650,
    anyOf: ["NETFLIX", 
      "SPOTIFY", 
      "DISNEY", 
      "PRIME VIDEO", 
      "APPLE.COM/BILL",  
      "OPENAI", 
      "CHATGPT",
      "YOUTUBE",
      "YOUTUBE PREMIUM",
      "CRAVE",
      "HULU",
      "PARAMOUNT",
      "PARAMOUNT+",
      "APPLE MUSIC",
      "PLAYSTATION",
      "PLAYSTATION NETWORK",
      "PSN",
      "XBOX",
      "NINTENDO",
      "STEAM",
      "EPIC GAMES",
      "SPOTIFY",
      "CINEPLEX",
    ],
  },

  // SHOPPING
  {
    category: SpendCategory.SHOPPING,
    priority: 600,
    anyOf: ["AMAZON", 
      "BEST BUY", 
      "WAL-MART", 
      "EBAY", 
      "IKEA", 
      "CANADIAN TIRE", 
      "URBAN BEHAVIOR",
      "H&M",
      "ZARA",
      "UNIQLO",
      "GAP",
      "OLD NAVY",
      "WINNERS",
      "MARSHALLS",
      "HOMESENSE",
      "SEPHORA",
      "SHOPPERS",
      "HOME DEPOT",
      "RONA",
      "LOWE'S",
      "LOWES",
      "STAPLES",
      "INDIGO",
      "CHAPTERS",
      "SPORT CHEK",
      "FOOT LOCKER",
      "ALDO",
      "ARDENE",
      "BATH AND BODY WORKS",
      "BATH & BODY WORKS",
      "HUDSON'S BAY",
      "HUDSONS BAY",
      "THE BAY",
      "MICHAELS",
      "DOLLARAMA",
      "MINISO",
    ],
  },

  // UTILITIES
  {
    category: SpendCategory.UTILITIES,
    priority: 550,
    anyOf: [
        "HYDRO",
        "ELECTRIC",
        "GAS BILL",
        rx("\\bWATER\\b"),
        "ROGERS",
        "BELL",
        "TELUS",
        "ENBRIDGE",
        "HYDRO ONE",
        "WATERLOO HYDRO",
        "FIDO",
        "KOODO",
        "VIRGIN MOBILE",
        "FREEDOM MOBILE",
        "SHAW",
        "VIDEOTRON",
        "COGECO",
        "ASTRAL",
        "TORONTO HYDRO",
        "ALECTRA",
        "HYDRO OTTAWA",
        "HYDRO QUEBEC",
        "HYDRO-QUÉBEC",
        "BC HYDRO",
        "ATCO",
        "EPCOR",
        "WATER BILL",
        "INTERNET",
        "MOBILE BILL",
        "CELLULAR",
    ],
  },

  // FEES
  {
    category: SpendCategory.FEES,
    priority: 500,
    anyOf: [
      rx("\\bfee\\b"),
      rx("\\bservice\\s?charge\\b"),
      rx("\\bnsf\\b"),
      "PURCHASE INTEREST",
      "MONTHLY FEE",
      "ANNUAL FEE",
      "OVERLIMIT FEE",
      "LATE FEE",
      "FOREIGN EXCHANGE FEE",
      "FX FEE",
      "CARD FEE",
      "BANK FEE",
      "INTEREST CHARGE",
      "PURCHASE INTEREST",
      "CASH ADVANCE FEE",
    ],
  },

  {
    category: SpendCategory.HEALTH,
    priority: 575,
    anyOf: [
      "SHOPPERS DRUG MART",
      "REXALL",
      "PHARMASAVE",
      "PHARMACY",
      "DENTAL",
      "MEDICAL",
      "WALK IN CLINIC",
      "CLINIC",
      "LIFELABS",
      "GOODLIFE",
      "FIT4LESS",
    ],
  },

  {
  category: SpendCategory.EDUCATION,
    priority: 580,
    anyOf: [
      "CONESTOGA",
      "MOHAWK COLLEGE",
      "UNIVERSITY OF WATERLOO",
      "WILFRID LAURIER",
      "TUITION",
      "COLLEGE",
      "UNIVERSITY",
      "UDACITY",
      "COURSERA",
      "UDEMY",
    ],
  },

  {
  category: SpendCategory.TRAVEL,
    priority: 690,
    anyOf: [
      "BOOKING.COM",
      "EXPEDIA",
      "AIRBNB",
      "MARRIOTT",
      "HILTON",
      "HOLIDAY INN",
      "HOTEL",
      "MOTEL",
      "RESORT",
    ],
  },
];